spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true

spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/bot
  username: postgres
  password: postgres

vkontakte:
  client:
    clientId: 6375922
    clientSecret: twWU8nL6yhja5pTXyt4R
    accessTokenUri: https://oauth.vk.com/access_token
    userAuthorizationUri: https://oauth.vk.com/authorize
#    tokenName: code
    authenticationScheme: query
    clientAuthenticationScheme: form
    grant-type: authorization_code

  resource:
    userInfoUri: https://api.vk.com/method/users.get?v=5.95


github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: debug
    org.springframework: debug
